### ISSUE TITLE
[Feature Request] RSS Feed

### ISSUE THREAD

**Issue by danrobi11** [emacstv/emacstv.github.io#2]
Title!

**Comment by xenodium** [comment]
Thanks for filing! @sachac built an org to json converter `emacstv-export-json`. Are you interested in giving the org -> rss converter a go?

**Comment by xenodium** [comment]
Ok this seems to work with elfeed.

<img width="1672" alt="Screenshot 2024-12-24 at 18 48 01" src="https://github.com/user-attachments/assets/7dff0336-2289-4b8e-95a6-056683f2e04e" />

Not given it much of a run. Give it a try https://emacs.tv/videos.rss

**Comment by danrobi11** [comment]
Yes https://emacs.tv/videos.rss is working as intended. Awesome! Thank you! Closing.
