### ISSUE TITLE
Tab icon not rendering correctly

### ISSUE THREAD

**Issue by danrobi11** [emacstv/emacstv.github.io#3]
Vieb 12.1.0
Electron 33.2.0 (was 30.0.6)
Chromium 130.0.6723.118 (was 124.0.6367.207)

![emacs tv-tab-icon-issue](https://github.com/user-attachments/assets/bfe95369-175b-44d8-a77b-2cbc3cf24b33)

**Comment by xenodium** [comment]
Thanks for filing. Chromium on macOS seems OK.

<img width="707" alt="image" src="https://github.com/user-attachments/assets/2edd5337-9fc5-413e-82f5-4ac60a88245a" />

<img width="379" alt="image" src="https://github.com/user-attachments/assets/6a978962-9755-4d65-9bab-1c4b2ff1db09" />

Can you still confirm this is an issue?

**Comment by xenodium** [comment]
Updated Chromium and seems ok too

<img width="362" alt="image" src="https://github.com/user-attachments/assets/3d8f5d8a-eb84-422c-8f06-1beb1b117770" />

<img width="716" alt="image" src="https://github.com/user-attachments/assets/4c7c9b99-ea41-4325-9385-5c74e0e4c839" />

**Comment by danrobi11** [comment]
Yes! installed chrome and it does render correctly. Must be on Vieb's end. Thanks! Therefor closing
