### ISSUE TITLE
UI: click on speaker name to browse by that speaker

### ISSUE THREAD

**Issue by sachac** [emacstv/emacstv.github.io#6]

**Comment by xenodium** [comment]
Had a first pass treating SPEAKERS as single items. I'll iterate to split comma-spearated ones.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/b2758bb8-771a-45c3-875e-083239914420" />

**Comment by xenodium** [comment]
![image](https://github.com/user-attachments/assets/d127e2ab-f148-4c93-a47c-c9930033f549)

**Comment by xenodium** [comment]
Gonna close this feature request as it's now implemented, but please re-open if not working as expected.
